### ISSUE TITLE
Filters are not registered during console (Kdyby\Console) commands yet

### ISSUE THREAD

**Issue by JanMikes** [Zenify/DoctrineFilters#3]
Hello, im using softDeletableFilter (very similiar to that one in doc), i found out that this filter is not registered yet/not used, while running commands from CLI. 
Is this feature or how can be this behavior changed?

**Comment by enumag** [comment]
I guess the problem is [here](https://github.com/Zenify/DoctrineFilters/blob/master/src/EventSubscriber/EnableFiltersSubscriber.php#L35). I'm not quite sure why the subscriber uses this event and not some other.

ping @TomasVotruba

**Comment by enumag** [comment]
As a workaround you could inject the filter manager into your command and call it manually for now.

**Comment by JanMikes** [comment]
@enumag thanks for the idea, this workaround seems to work.

**Comment by TomasVotruba** [comment]
That's a bug. Since these might be 2 separated applications, I'd add Symfony Console Event (you have to find the specific name, I don't remember): 

``` php
/**
 * {@inheritdoc}
 */
public static function getSubscribedEvents()
{
    return [
        NetteApplicationEvents::ON_PRESENTER => 'registerFilters',
        ..\ConsoleEvent::RUN => 'registerFilters'
    ];
}
```

**Comment by enumag** [comment]
@TomasVotruba Even so why onPresenter and not onRequest or even Container::onInitialize?

**Comment by JanMikes** [comment]
The event is `Symfony\Component\Console\ConsoleEvents::COMMAND`
As well i think [there should be added check](https://github.com/Zenify/DoctrineFilters/blob/master/src/FilterManager.php#L56) to prevent duplicate enabling a filter?

**Comment by TomasVotruba** [comment]
@enumag There was issue with onRequest - the presenter name not available yet.
Softdelete and similar filters require to detect if it's Admin/Front presenter.

@Lexinek Yep, the check is required. Have you tried adding the event? Did it solve your issue?

**Comment by JanMikes** [comment]
@TomasVotruba not yet, but later today i will try. As well i can send PR for this if you want. Not sure about tests though, if i will be able to cover it.

**Comment by TomasVotruba** [comment]
@Lexinek As for this package, it's under @enumag 's maintenance.

**Comment by enumag** [comment]
@Lexinek PR would be appriciated. Tests would be appriciated but I might merge it even without them (depends on what will be changed).

**Comment by TomasVotruba** [comment]
Ping @Lexinek 

Feel free sending PR when ready.

**Comment by JanMikes** [comment]
@TomasVotruba thank you, i have already forgot about this issue :-)

**Comment by TomasVotruba** [comment]
Might check it, gimme a sec :)

**Comment by TomasVotruba** [comment]
Solved!

@Lexinek Thanks for pointing out that Console event. It was much easier to solve it with that hint.

**Comment by JanMikes** [comment]
I thank you @TomasVotruba for fixing!
